### ISSUE TITLE
Note: update CSS

### ISSUE THREAD

**Issue by ts-vadim** [nkg-17/math-tests#4]
**Icons**: https://fontawesome.com/icons

```css
.TestBody {
    font-size: 1.05rem;
    letter-spacing: -.03rem;
    line-height: 1.5rem;
    text-align: left;
    word-spacing: .2rem;
}
```
To
```css
.TestPanel {
    box-shadow: 0px 0px 150px 15px rgba(0,0,0,0.3);
}

.TestBody {
    font-size: 1.5rem;
    height: 50vh;
    letter-spacing: -.03rem;
    line-height: 1.9rem;
    max-height: 50vh;
    overflow-y: scroll;
    text-align: left;
    word-spacing: .4rem;
    scrollbar-width: none;
}

.TestHeaderTitle {
    font-size: 2.5rem;
}
```
